[features]
seeds = false
skip-lint = false
[programs.devnet]
sol_survey = "9xUCA4apJEJRUVSpyYrXwjC12mTGYRgBJSd38focKqNC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jaymanyoo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
